version: "1.0"
scanner:
  # global setting
  global:
    default_arches:
      - linux/amd64
      - linux/arm64
    # support format: 24h, 1d, 1w, 30m
    default_interval: "24h"
    output:
      repo: https://github.com/Ascend/cann-container-image
      path: Security/reports

# period scan repo setting

# specific image scan
images:
  - image: "cann"
    tags:
      - tag: "docker.io/ascendai/cann:latest"
        # override global scan cycle
        interval: "2h"
        disable: true
        arches:
          - linux/arm64

      - tag: "quay.io/ascend/cann:8.2.rc1-910-openeuler22.03-py3.11"
        interval: "2d"
        disable: true
      - tag: "quay.io/ascend/cann:latest"
        interval: "2d"  
        arches:
          - linux/arm64

  - image: "cann"
    tags:
      - tag: "docker.io/ascendai/cann:8.2.rc1-910b-ubuntu22.04-py3.11"
        # disable this tag scan
        disable: true                   

  # use global scan cycle
  - image: "cann"
    tags:
      - tag: "docker.io/ascendai/cann:8.1.rc1-910b-ubuntu22.04-py3.11"

# notice setting (option)
notifications:
  email:
    enabled: true
    recipients:
      - "security@example.com"
    smtp_server: "smtp.example.com:587"

  slack:
    enabled: false
    webhook_url: ""
