name: Build CANN Image

on:
  push:
    branches:
    paths:
      - ".github/workflows/build_cann.yml"
      - "cann/**"
      - "build_arg.json"

  pull_request:
    branches:
      - "main"
    paths:
      - ".github/workflows/build_cann.yml"
      - "cann/**"
      - "build_arg.json"

jobs:
  prepare:
    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

    outputs:
      matrix: ${{ steps.get-build-matrix.outputs.matrix }}
      
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get build matrix
        id: get-build-matrix
        run: |
          MATRIX=$(jq -c '.cann | map({target: .tags[0],
              arches: [
                {arch: "x86_64", runner: "linux-x86_64"},
                {arch: "aarch64", runner: "ubuntu-22.04-arm"}
              ]
            }) | {include: [.[] | .arches[] as $arch | {target: .target, arch: $arch.arch, runner: $arch.runner}]}' build_cann_arg.json)
          echo "matrix=$MATRIX" >> $GITHUB_OUTPUT

  build:
    needs: prepare 
    strategy:
      matrix: ${{ fromJson(needs.prepare.outputs.matrix) }}
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image
        uses: docker/build-push-action@v6
        id: build
        with: 
          platforms: ${{ matrix.arch }}
          file: ${{ github.workspace }}/cann/${{ matrix.target }}/Dockerfile
          context: ${{ github.workspace }}/cann/${{ matrix.target }}
          outputs: type=image
          provenance: false